version: '3'
services:
  parking_control:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: parking_control
    container_name: parking_control
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/parking_control_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dev123
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8
    container_name: db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=parking_control_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev123
      - MYSQL_ROOT_PASSWORD=dev123
    volumes:
      - ./database:/var/lib/mysql

volumes:
  database: